In [152]:
import torch
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [153]:
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time -start_time
print(f"{elapsed_time:.8f}")

0.00100017


In [154]:
scalar = torch.tensor(7)
scalar.item()

7

In [155]:
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [156]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix.ndim

2

In [157]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor.shape

torch.Size([1, 3, 3])

In [158]:
rendom_tensor = torch.rand(size=(3,4))
rendom_tensor, rendom_tensor.dtype

(tensor([[0.9694, 0.3688, 0.1241, 0.8777],
         [0.6105, 0.3384, 0.7284, 0.0499],
         [0.4504, 0.8467, 0.7597, 0.7435]]),
 torch.float32)

In [159]:
out = torch.zeros(size=(3,4))
out.ndim

torch.ones(size=(3,4))


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [160]:
out = torch.arange(0., 100., 4.2)
out

tensor([ 0.0000,  4.2000,  8.4000, 12.6000, 16.8000, 21.0000, 25.2000, 29.4000,
        33.6000, 37.8000, 42.0000, 46.2000, 50.4000, 54.6000, 58.8000, 63.0000,
        67.2000, 71.4000, 75.6000, 79.8000, 84.0000, 88.2000, 92.4000, 96.6000])

In [161]:
torch.ones_like(out)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.])

In [162]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float64)
print(float_16_tensor.device)

cpu


In [163]:
%%time
tensor = torch.tensor([[1,2,3], [4,5,6]] )
tensor2 = torch.tensor([[1,2],[3,4],[5,6]])
print(tensor)
print(tensor2)

tensor @ tensor2

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
CPU times: total: 0 ns
Wall time: 999 µs


tensor([[22, 28],
        [49, 64]])

In [164]:
probabilities = torch.tensor([0.1, 0.9])

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [165]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [166]:
torch.tril(torch.ones(5,5))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [167]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [168]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [169]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [170]:
torch.tensor([[1,2], [3,4], [5,6]]).transpose(0,1)

tensor([[1, 3, 5],
        [2, 4, 6]])

In [171]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor1 = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor1


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [172]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([-1.1683,  1.8399, -0.2688], grad_fn=<SqueezeBackward4>)
