In [284]:
import torch
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [285]:
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time -start_time
print(f"{elapsed_time:.8f}")

0.00100088


In [286]:
scalar = torch.tensor(7)
scalar.item()

7

In [287]:
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [288]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix.ndim

2

In [289]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor.shape

torch.Size([1, 3, 3])

In [290]:
rendom_tensor = torch.rand(size=(3,4))
rendom_tensor, rendom_tensor.dtype

(tensor([[0.5191, 0.5335, 0.5375, 0.7058],
         [0.4275, 0.2761, 0.8396, 0.1563],
         [0.1072, 0.7261, 0.3241, 0.8892]]),
 torch.float32)

In [291]:
out = torch.zeros(size=(3,4))
out.ndim

torch.ones(size=(3,4))


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [292]:
out = torch.arange(0., 100., 4.2)
out

tensor([ 0.0000,  4.2000,  8.4000, 12.6000, 16.8000, 21.0000, 25.2000, 29.4000,
        33.6000, 37.8000, 42.0000, 46.2000, 50.4000, 54.6000, 58.8000, 63.0000,
        67.2000, 71.4000, 75.6000, 79.8000, 84.0000, 88.2000, 92.4000, 96.6000])

In [293]:
torch.ones_like(out)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.])

In [294]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float64)
print(float_16_tensor.device)

cpu


In [295]:
%%time
tensor = torch.tensor([[1,2,3], [4,5,6]] )
tensor2 = torch.tensor([[1,2],[3,4],[5,6]])
print(tensor)
print(tensor2)

tensor @ tensor2

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
CPU times: total: 0 ns
Wall time: 2.52 ms


tensor([[22, 28],
        [49, 64]])

In [296]:
probabilities = torch.tensor([0.1, 0.9])

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([0, 1, 1, 1, 1, 1, 0, 1, 1, 1])

In [297]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [298]:
torch.tril(torch.ones(5,5))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [299]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [300]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [301]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [302]:
torch.tensor([[1,2], [3,4], [5,6]]).transpose(0,1)

tensor([[1, 3, 5],
        [2, 4, 6]])

In [303]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor1 = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor1


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [304]:
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([ 2.1885, -5.6349, -1.9542], grad_fn=<SqueezeBackward4>)


In [305]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [306]:
a = torch.rand(2, 3, 5)
x, y, z = a.shape

a = a.view(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])


In [307]:
a = torch.arange(3, 70, 3)
a

b = torch.ones_like(a)
b

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [308]:
tensor = torch.rand(3,2)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 2])
torch.float32
cpu


In [309]:
torch.manual_seed(43)
inputs = torch.tensor([[1, 2, 3],
                         [3, 4, 5],
                         [5, 6, 7]], dtype=torch.float32)


linear = torch.nn.Linear(in_features=3, out_features=6)
linear

x = inputs
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 3])

Output:
tensor([[ 1.0965, -2.8220, -0.4933,  0.1515,  0.0263, -0.2558],
        [ 1.2616, -4.9464, -0.7139,  0.6095,  0.2345, -0.4648],
        [ 1.4268, -7.0709, -0.9345,  1.0674,  0.4427, -0.6739]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [310]:
tensor = torch.tensor([3.3,2.34,4.123,6.34,12.123], dtype=torch.float)
tensor = tensor.type(torch.int32)
tensor

tensor([ 3,  2,  4,  6, 12], dtype=torch.int32)

In [311]:
tensor = torch.arange(2,6,1)
tensor = torch.reshape(tensor, (2,2))
print(tensor)
tensor.view(4)

tensor([[2, 3],
        [4, 5]])


tensor([2, 3, 4, 5])

In [312]:
tensor1 = torch.randint(size=(3,2), low=2, high=6)
tensor2 = torch.randint(size=(3,2), low=2, high=6)
tensorout = torch.stack((tensor1, tensor2))
tensorout.shape

torch.Size([2, 3, 2])

In [313]:
x = torch.arange(1, 10).reshape(1,3, 3)
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [314]:
x[0,:, 1]

tensor([2, 5, 8])

In [315]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [316]:
torch.manual_seed(43)
random_tensor1 = torch.rand(3,4)
torch.manual_seed(43)
random_tensor2 = torch.rand(3,4)

print(random_tensor1)
print(random_tensor2)
random_tensor1 == random_tensor2

tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])